esphome:
  name: minisplit
  name_add_mac_suffix: true

esp8266:
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # ap: {} # connect to the minisplit-XXXXX wifi network and then visit http://192.168.4.1 to set your wifi credentials

captive_portal:

debug:

logger:
  level: INFO
  baud_rate: 0

api:

web_server:
  port: 80

ota:
  - platform: esphome

uart:
  tx_pin: 12
  rx_pin: 14
  baud_rate: 9600

button:
  - platform: template
    name: AC Display Toggle
    id: midea_display_toggle
    icon: mdi:theme-light-dark
    on_press:
      midea_ac.display_toggle:
  - platform: template
    name: AC Swing Step
    id: midea_swing_step
    icon: mdi:tailwind
    on_press:
      midea_ac.swing_step:

climate:
  - platform: midea
    name: "Mini Split"
    id: midea_climate
    period: 1s
    timeout: 2s
    num_attempts: 3
    autoconf: false
    beeper: true
    visual:
      min_temperature: "60 °F"
      max_temperature: "90 °F"
      temperature_step: "1 °F"
    supported_modes:
      - FAN_ONLY
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
    custom_fan_modes:
      - SILENT
      - TURBO
    supported_presets:
      - ECO
      - BOOST
      - SLEEP
    custom_presets:
      - FREEZE_PROTECTION
    supported_swing_modes:
      - VERTICAL
      - HORIZONTAL
      - BOTH
    outdoor_temperature:
      name: AC Outdoor Temperature
    power_usage:
      name: AC Power Usage
    humidity_setpoint:
      name: AC Indoor Humidity

switch:
  - platform: template
    name: AC Beeper
    id: midea_beeper
    icon: mdi:volume-source
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    turn_on_action:
      midea_ac.beeper_on:
    turn_off_action:
      midea_ac.beeper_off:

sensor:
  - platform: wifi_signal
    name: AC Wi-Fi Signal
    update_interval: 60s
  - platform: uptime
    name: "Uptime"
    id: uptime_sec
    internal: true
  - platform: template
    name: AC Uptime Days
    lambda: |-
      return (id(uptime_sec).state/60)/60/24;
    icon: mdi:clock-start
    unit_of_measurement: days
    update_interval: 60s

script:
  - id: on_button_click
    then:
      midea_ac.power_toggle:
